HW-1: Building Blocks of OOP. Part-1
StashiKu/Software-Designs-and-Algorithms pull request #1
Opened 2023-02-22 12:33 UTC by StashiKu

# 📚 Home Task

The home task should be done using TypeScript.

## Specific Steps

1. Create a `Point` class, which creates 2 dimensional point with coordinates. It
   should contain:
  [x] two instance variables `x` and `y`;
  [x] default constructor which creates a point at the location of (0, 0);
  [x] overloaded constructor (use multiple constructors declaration for Typescript)
    which creates a point by `x` and `y` coordinates;
  [x] `toString()` method should return a `Point` class stringified representation in
    format: `"(x, y)"`;
  [x] `distance()` method should be overloaded (use multiple methods declaration for
    Typescript) with next implementations:
    [x] no args: distance from this point to (0, 0);
    [x] `distance(other: Point)` - distance from this point to a given instance of
      `Point`;
    [x] `distance(x, y)` - distance from this point to a given point (x, y).

2. Create abstract superclass called `Shape`, which contains:
  [x] two protected instance variables: `color` (string), `filled`
    (boolean) and `points` (Point[]);
  [x] overloaded constructor (use multiple constructors declaration for Typescript): a
    constructor that takes a list of `points` and initializes the color to `"green"`
    and filled to `true` by default, and a constructor that takes a list of `points`,
    the `color` and `filled` properties;
  [x] Make sure that the `Shape` has at least 3 points (2 points is just a line).
  [x] `toString()` method that returns `"A Shape with color of xxx and filled/Not
    filled. Points: (x1, y1), (x2, y2)..."`;
  [x] `getPerimeter()` that calculates the perimeter using `Point.distance` method;

3. Create class `Triangle` that takes 3 points as it's vertices. Triangle must inherit
   `Shape` abstract class. `Triangle` should contain:

  [x] a constructor (use multiple constructors declaration for Typescript) which creates
    `Triangle` class using three instances of `Point` class, may also provide color and
    filled properties;
  [x] override `toString()` method, it should return a `Triangle` class stringified
    representation in format `"Triangle[v1=(x1, y1),v2=(x2, y2),v3=(x3, y3)]"`;
  [x] override `getType()` method, which prints `"equilateral triangle"` if all the three
    sides are equal, `"isosceles triangle"` if any two of the three sides are equal, or
    `"scalene triangle"` if all sides are different.

## Evaluation criteria

2. Only some classes were implemented.
3. Some classes were not implemented.
4. Some required methods are missing. All `@ts-nocheck` comments are removed and there are no TypeScript warnings exist after that.
5. All tasks are implemented to a full extent and all tests are passed successfully (`npm run test`). All `@ts-nocheck` comments are removed and there are no TypeScript warnings exist after that.

2023-02-25 21:32 UTC, metam0rphus requested changes

2023-02-25 21:32 UTC, metam0rphus commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +    public x: number;
better to have it private

2023-02-25 21:32 UTC, metam0rphus commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +    public distance(...arg: any): number | null {
usage of "any" is bad practice

2023-02-25 21:32 UTC, metam0rphus commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +        const exponent = 2;
Math.hypot

2023-02-25 21:32 UTC, metam0rphus commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +        return null;
it shouldn't return null

2023-02-25 21:32 UTC, metam0rphus commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Triangle.ts
> +    constructor(p1: Point, p2: Point, p3: Point, color?: string, filled?: boolean) {
just {super([v1, v2, v3], color, filled);}

2023-02-25 21:32 UTC, metam0rphus commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Triangle.ts
> +    public toString(): string {
toString(): string {
        const [v1, v2, v3] = this.points;
        return `Triangle[v1=${v1},v2=${v2},v3=${v3}]`
    }

2023-02-26 05:01 UTC, StashiKu commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +    public x: number;
fix

2023-02-26 05:01 UTC, StashiKu commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +    public distance(...arg: any): number | null {
fixed

2023-02-26 05:01 UTC, StashiKu commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +        const exponent = 2;
fixed

2023-02-26 05:01 UTC, StashiKu commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Point.ts
> +        return null;
fixed

2023-02-26 05:01 UTC, StashiKu commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Triangle.ts
> +    constructor(p1: Point, p2: Point, p3: Point, color?: string, filled?: boolean) {
fixed

2023-02-26 05:01 UTC, StashiKu commented on HW-1-Building-Blocks-of-OOP-Part-1/src/Triangle.ts
> +    public toString(): string {
fixed

2023-03-05 13:42 UTC, metam0rphus approved these changes

2023-03-05 13:45 UTC, merged